name: Automatically Deployment

on: 
  push:
    branches: main
jobs: 
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          
          
      - name: Setting .env
        run: | 
          echo "REACT_APP_OPENAI_KEY =$REACT_APP_OPENAI_KEY" >> .env
        env:  
          REACT_APP_OPENAI_KEY: ${{ secrets.REACT_APP_OPENAI_KEY }}
          
      - name: Install Dependencies
        run: npm install
        
      - name: Install gh-pages globally
        run: npm install -g gh-pages --save-dev
        
      - name: Build
        run: npm run build
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
          publish_dir: ./build